-- CREATE DATABASE C243217;

USE C243217;

-- CREATE TABLE students(
-- 	id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(20) NOT NULL,
--     dept VARCHAR(30) NOT NULL,
--     dob DATE
-- );

ALTER TABLE students ADD COLUMN email VARCHAR(50) UNIQUE NOT NULL;